bind = $mainMod, return, exec, $terminal
bind = $mainMod, Q, killactive,
bind = $mainMod, M, exec, command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit
bind = $mainMod, F, exec, $fileManager
bind = $mainMod, tab, fullscreen, 0
bind = $mainMod, V, togglefloating,
bind = $mainMod, space, exec, $ipc launcher toggle
bind = $mainMod, L, exec, $ipc lockScreen lock
bind = $mainMod, P, pseudo, # dwindle
bind = $mainMod, J, layoutmsg, togglesplit # dwindle
bind = $mainMod, O, layoutmsg, swapsplit # dwindle
bind = $mainMod, C, exec, hyprpicker -a

# Move focus with mainMod + arrow keys
bind = $mainMod, left, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d

# Move windows in current workspace
bind = $mainMod SHIFT, left, movewindow, l
bind = $mainMod SHIFT, right, movewindow, r
bind = $mainMod SHIFT, up, movewindow, u
bind = $mainMod SHIFT, down, movewindow, d

# Create a resize mode to edit widow sizes
bind = $mainMod, R, submap, resize
submap = resize
bind = , right, resizeactive, $resizeMod 0
bind = , left, resizeactive, -$resizeMod 0
bind = , up, resizeactive, 0 -$resizeMod
bind = , down, resizeactive, 0 $resizeMod
bind = , escape, submap, reset
submap = reset

# Switch workspaces with mainMod + [0-9]
bind = $mainMod, 1, split-workspace, 1
bind = $mainMod, 2, split-workspace, 2
bind = $mainMod, 3, split-workspace, 3
bind = $mainMod, 4, split-workspace, 4

# We can't use numbers directly so we'll just use these
bind = $mainMod, bracketleft, split-movetoworkspace, -1
bind = $mainMod, bracketright, split-movetoworkspace, +1
bind = $mainMod SHIFT, bracketleft, split-changemonitor, -1
bind = $mainMod SHIFT, bracketright, split-changemonitor, +1

# Screenshot capture
bind = , PRINT, exec, grim -g "$(hyprctl activewindow -j | jq -r '"\(.at[0]),\(.at[1]) \(.size[0])x\(.size[1])"')" - | tee "$HYPRSHOT_DIR/window-$(date +%Y-%m-%d-%H%M%S).png" | wl-copy --type image/png
bind = $mainMod, PRINT, exec, grim - | tee "$HYPRSHOT_DIR/all-displays-$(date +%Y-%m-%d-%H%M%S).png" | wl-copy --type image/png
bind = $mainMod SHIFT, S, exec, hyprshot -m region

# Scroll through existing workspaces with mainMod + scroll
# bind = $mainMod, mouse_down, workspace, e+1
# bind = $mainMod, mouse_up, workspace, e-1

# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow
