plugin {
    split-monitor-workspaces {
        count = 4
        enable_wrapping = 0
        keep_focused = 1
        enable_notifications = 0
        enable_persistent_workspaces = 1
        link_monitors = 0
        monitor_priority = DP-3,DP-1,DP-2,HDMI-A-1

        max_workspaces = DP-3, 4
        max_workspaces = DP-1, 4
        max_workspaces = DP-2, 4
        max_workspaces = HDMI-A-1, 4
    }
}
