windowrule {
    name = mpv-float
    match:class = ^(mpv)$
    float = true
    max_size = 1920 1080
}

windowrule {
    name = imv-float
    match:class = ^(imv)$
    float = true
    max_size = 1920 1080
}

windowrule {
    name = amberol-float
    match:title = ^(Amberol)$
    float = true
}

windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}

# Force floating Windows for certain applications
windowrule = float on, center on, match:class ^(dev.noctalia.noctalia-qs)$
windowrule = float on, center on, match:class ^(steam)$, match:title negative:Steam
